config/routes.rb
Rails.application.routes.draw do

  root to: 'store#index', as: 'store'
  #get 'item_search/index'
  resources :items_search, only: :index
  resources :reviews
  resources :shipping_addresses
  resources :orders

  resources :carts, only: :show
  resources :line_items
  resources :categories, only: [:show, :index] do
    resources :items
  end
  resources :items do
    resources :reviews;
  end
  #resources :categories, only: :show



  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '*unmatched_route', to: 'application#raise_not_found'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy
  has_many :items, through: :line_items

  def total
    line_items.collect { |li|
      li.valid? ? (li.quantity * li.item.price) : 0
    }.sum
  end

  def number_of_item
  	line_items.collect(&:quantity).sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  #validates :title, uniqueness: true
  #validates :title, :category, :price, :description, :image, presence: true
  belongs_to :category
  has_many :line_items
  has_many :reviews
  has_attached_file :image, styles: { large:"450x600", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  def update_inventory(inventory)
  	item_to_hash = self.attributes
  	item_to_hash["inventory"] -= inventory
  	self.update(item_to_hash)
  end
end

app/models/item_search_term.rb
class ItemSearchTerm
  attr_reader :where_clause, :where_args, :order

  def initialize(search_term)
    search_term = search_term.downcase

    @where_clause = ""
    @where_args = {}

    searchByTitle(search_term)
  end

  def searchByTitle(search_term)
    @where_clause << case_insensitive_search(:title)
    @where_args[:title] = starts_with(search_term)
    @order = "title ASC"
  end

  def starts_with(search_term)
    "%" + search_term + "%"
  end

  def case_insensitive_search(field_name)
    "lower(#{field_name}) like :#{field_name}"
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end

  def sub_total
    unit_price * quantity
  end

  def finalize
    self[:unit_price] = unit_price
    self[:sub_total] = self[:quantity] * self[:unit_price]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :user
  has_one :cart, through: :user
  has_one :shipping_address, through: :user

  before_create :set_order_status
  before_save :set_total

  def total
  	cart.total
  end

  private

  def set_order_status
	self.order_status_id = 1
  end

  def set_total
  	self[:total] = total
  end


end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item

  def updated_at
    self[:updated_at].strftime('%b %d, %Y');
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :user
  belongs_to :order

  validates_format_of :zip_code,
                  with: /\A\d{5}-\d{4}|\A\d{5}\z/,
                  errors: "should be 12345 or 12345-1234",
                  allow_blank: true
  validates :name, :address_line1, :address_line2, :city, :state, :country, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_one :shipping_address
	has_one :cart
	belongs_to :current_cart, class_name: "Cart"
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:twitter, :facebook, :google_oauth2, :github, :linkedin]



  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@line_items = current_cart.line_items
    render json: @line_items
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #before_action :authenticate_user!, except: :show
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  PAGE_SIZE = 9
  # GET /items
  # GET /items.json
  def index
    @page = (params[:page] || 0).to_i
    if params[:category_id] && Category.find_by(id: params[:category_id])
      @items = Category.find_by(id: params[:category_id]).items.offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
    else
      @items = Item.all.offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
    end

    #authorize @items
    respond_to do |format|
      #format.html { render :index}
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    if params[:category_id]
      if !@item
        @category = Category.find_by(id: params[:category_id])
        flash[:alert] = "Item not found"
        redirect_to category_item_path(@category)
      end
    end

    respond_to do |format|
      format.html { render :show}
      format.json { render json: @item}
    end
  end

  # GET /items/new
  def new
    @item = Item.new
    authorize @item
  end

  # GET /items/1/edit
  def edit
    authorize @item
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    authorize @item
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    authorize @item
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    authorize @item
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :inventory, :price, :description, :category_id, :image)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    #@categories = Category.all
    render 'layouts/application'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/item_search_helper.rb
module ItemSearchHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/show.html.erb
<div class="container">
  <% if !@line_items.empty? %>
	<table id="cart" class="table table-hover table-condensed">
    				<thead>
						<tr>
							<th style="width:50%">Item</th>
							<th style="width:10%">Price</th>
							<th style="width:8%">Quantity</th>
							<th style="width:22%" class="text-center">Subtotal</th>
							<th style="width:10%">Delete</th>
						</tr>
					</thead>
					<tbody>
            <% @line_items.each do |line_item| %>
						<tr>
							<td data-th="Product">
								<div class="row">
									<div class="col-sm-2 hidden-xs">
                    <%= image_tag line_item.item.image.url(:thumb) %>
                  </div>
									<div class="col-sm-10">
										<h4 class="nomargin">
                      <%= link_to line_item.item.title, item_path(line_item.item)%>
                    </h4>
										<p><%= line_item.item.description %></p>
									</div>
								</div>
							</td>
							<td data-th="Price">
                <%= "$#{line_item.item.price.to_f/100}" %>
              </td>
							<td data-th="Quantity">
								<%= line_item.quantity %>
							</td>
							<td data-th="Subtotal" class="text-center">
                <%= "$#{line_item.sub_total.to_f/100}" %>
               </td>
							<td class="actions" data-th="">
								<%= button_to 'Remove', line_item_path(line_item), method: :delete, class: "btn btn-danger btn-sm" %>
							</td>
						</tr>
            <%end%>
					</tbody>
					<tfoot>
						<tr class="visible-xs">
							<td class="text-center"><strong></strong></td>
						</tr>
						<tr>
							<td>
                <%= link_to "Continue Shopping",store_path, class: "btn btn-small btn-warning" %>
              </td>
							<td colspan="2" class="hidden-xs"></td>
							<td class="hidden-xs text-center"><strong>Total <%= "$#{current_cart.total.to_f/100}"%></strong></td>
							<td>
                
                  <%= button_to 'Checkout', orders_path, method: :post, class: "btn btn-success btn-sm" %>
                
              </td>
						</tr>
					</tfoot>
				</table>
        <%else%>
        <div class="panel panel-default col-md-offset-2">
          <div class="card card-block text-xs-center panel-body col-md-offset-4">
            <h4 class="card-title text-info">You don't have items in your cart.</h4>
            <%= link_to "Continue Shopping",store_path, class: "btn btn-small btn-warning" %>
          </div>
        </div>
        <%end%>
</div>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true, class: "form-control"%>
  </div>

  <div class="field">
    <%= f.label :inventory %><br />
    <%= f.number_field :inventory, min: 0, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price, min: 0, step: '0.01' ,autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.collection_select :category_id, Category.all, :id, :title, prompt: true %>
  </div>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 6, autofocus: true, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
     <div class="table-responsive">
       <table id="mytable" class="table table-bordred table-striped">
         <thead>
             <th>Title</th>
             <th>Price</th>
             <th>Inventory</th>
             <th>CategoryId</th>
             <th>Description</th>
             <th>Edit</th>
             <th>Delete</th>
         </thead>
         <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%=link_to item.title, item_path(item)%></td>
            <td><%=item.price%></td>
            <td><%=item.inventory%></td>
            <td><%=item.category_id%></td>
            <td><%=item.description%></td>
            <td><%= link_to '<span class="btn btn-md btn-info fa fa-pencil"></span>'.html_safe ,
              edit_item_path(item) %>
           </td>
            <td><%= link_to '<span class="btn btn-md btn-danger fa fa-trash"></span>'.html_safe,
              item_path(item), method: :delete %>
            </td>
          </tr>

          <%end%>
        </tbody>

      </table>
  </div>
 </div>
</div>
</div>


<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="content-wrapper">
  <div class="item-container">
		<div class="container-fluid">
			<div class="col-xs-12 col-sm-12 col-md-12">
				<div class="item col-xs-12 col-sm-12 col-md-4">
						<%= image_tag @item.image.url(:large), class: "img-responsive"%>
				</div>
				<div class="col-md-4">
					<div class="item-title"><strong><%= @item.title %></strong></div>
					<div class="item-desc"></div>
					<hr>
					<div class="item-price">$<%= @item.price.to_f/100 %></div>

	        <%if @item.inventory < 5 && @item.inventory > 0 %>
	          <div class="item-stock"><strong>There are only <%= @item.inventory %> left in stock.</strong></div>
	        <% elsif @item.inventory < 0 %>
	          <div class="item-out">Out of Stock</div>
	        <%else%>
	          <div class="item-stock">In Stock</div>
	        <% end %>
	        <hr>
	        <% if  @item.inventory > 0 %>
						<div class="btn-group cart">
						 <%= button_to 'Add to Cart', line_items_path(item_id: @item.id ), class: "btn btn-info"%>
						</div>
	        <%end%>

					<div class="btn-group wishlist">
						<%= button_to 'Add wishlist', store_path, method: :get, class: "btn btn-danger" %>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid">
      <div class="col-xs-12 col-sm-12 col-md-12 item-info">
            <button id="open-review-box">Write a customer review</button>
      </div><br />
      <div class="row" id="post-review-box">
        <div class="col-md-12">
          <form action="" name="review">
            <div class="field">
              <input placeholder="Title" id="title" name="title" required></input>
            </div>
            <div class="field">
              <textarea placeholder="Enter your review here..." class="form-control" cols="50" id="content" name="content" required></textarea>
            </div>
            <div class="actions">
              <input id="itemId" value ="<%= @item.id %>" type="hidden" required>
              <% unless current_user.nil? %>
                <input id="userId" value ="<%= current_user.id %>" type="hidden" required>
              <%end%>
              <button id="close-review-box" class="btn btn-sm btn-danger">cancle</button>
              <button id="post-review" class="btn btn-sm btn-success">save</button>
            </div>
        </form>
        </div>
      </div>
			<div class="col-xs-12 col-sm-12 col-md-12 item-info">
					<ul id="myTab" class="nav nav-tabs nav_tabs">
						<li class="active"><a href="#description" data-toggle="tab">DESCRIPTION</a></li>
						<li><a href="#review" data-toggle="tab" data-id="<%= @item.id%>">REVIEWS</a></li>
					</ul>
				<div id="myTabContent" class="tab-content">
					<div class="tab-pane fade in active" id="description">
						<section class="container">
							<h3><%=@item.title%>:</h3><br />
							<%= @item.description%>
						</section>
					</div>
					<div class="tab-pane fade" id="review">
					</div>
			</div>
			<hr>
		</div>
	</div>
	</div>
</div>