config/routes.rb
Rails.application.routes.draw do

  root to: 'store#index', as: 'store'
  #get 'item_search/index'
  resources :items_search, only: :index
  resources :reviews
  resources :shipping_addresses
  resources :orders

  resources :carts, only: :show
  resources :line_items
  resources :categories, only: [:show, :index] do
    resources :items
  end
  resources :items do
    resources :reviews;
  end
  #resources :categories, only: :show



  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '*unmatched_route', to: 'application#raise_not_found'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy
  has_many :items, through: :line_items

  def total
    line_items.collect { |li|
      li.valid? ? (li.quantity * li.item.price) : 0
    }.sum
  end

  def number_of_item
  	line_items.collect(&:quantity).sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  #validates :title, uniqueness: true
  #validates :title, :category, :price, :description, :image, presence: true
  belongs_to :category
  has_many :line_items
  has_many :reviews
  has_attached_file :image, styles: { large:"450x600", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  def update_inventory(inventory)
  	item_to_hash = self.attributes
  	item_to_hash["inventory"] -= inventory
  	self.update(item_to_hash)
  end
end

app/models/item_search_term.rb
class ItemSearchTerm
  attr_reader :where_clause, :where_args, :order

  def initialize(search_term)
    search_term = search_term.downcase

    @where_clause = ""
    @where_args = {}

    searchByTitle(search_term)
  end

  def searchByTitle(search_term)
    @where_clause << case_insensitive_search(:title)
    @where_args[:title] = starts_with(search_term)
    @order = "title ASC"
  end

  def starts_with(search_term)
    "%" + search_term + "%"
  end

  def case_insensitive_search(field_name)
    "lower(#{field_name}) like :#{field_name}"
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end

  def sub_total
    unit_price * quantity
  end

  def finalize
    self[:unit_price] = unit_price
    self[:sub_total] = self[:quantity] * self[:unit_price]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :user
  has_one :cart, through: :user
  has_one :shipping_address, through: :user

  before_create :set_order_status
  before_save :set_total

  def total
  	cart.total
  end

  private

  def set_order_status
	self.order_status_id = 1
  end

  def set_total
  	self[:total] = total
  end


end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item

  def updated_at
    self[:updated_at].strftime('%b %d, %Y');
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :user
  belongs_to :order

  validates_format_of :zip_code,
                  with: /\A\d{5}-\d{4}|\A\d{5}\z/,
                  errors: "should be 12345 or 12345-1234",
                  allow_blank: true
  validates :name, :address_line1, :address_line2, :city, :state, :country, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_one :shipping_address
	has_one :cart
	belongs_to :current_cart, class_name: "Cart"
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:twitter, :facebook, :google_oauth2, :github, :linkedin]



  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/shipping_addresses_controller.rb
class ShippingAddressesController < ApplicationController
  before_action :find_address, only: [:new, :edit, :update, :destroy]

    def new
      @order = Order.find_by(id: params[:order_id])
      if @shipping_address
        @shipping_address.order = @order
        @shipping_address.save
        redirect_to edit_shipping_address_path(@shipping_address)
      else
        
        @shipping_address = ShippingAddress.new(order: @order, user: current_user)
      end

    end

    def create
      
      @shipping_address = ShippingAddress.new(shipping_address_params)
      
      if @shipping_address.save
        flash[:notice] = 'Thank You! for Your Orders.'
        redirect_to store_path
          
      else
        flash[:notice] = @shipping_address.errors
        render :new
          
      end
     end 

    def edit
    end

    def update
      
      if @shipping_address.update(shipping_address_params)
        flash[:notice] = 'Thank You! for Your Orders.'
        redirect_to store_path
      else
        flash[:notice] = @shipping_address.errors
        render :edit 
      end
      
    end

    def destroy

    end

    private

      def find_address
        @shipping_address = ShippingAddress.find_by(user_id: current_user.id)
      end

      def shipping_address_params
        params.require(:shipping_address).permit(:name, :address_line1, :address_line2, :city,
          :state, :zip_code, :country, :user_id, :order_id)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/item_search_helper.rb
module ItemSearchHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/shipping_addresses/_form.html.erb
<%= form_for(shipping_address) do |f| %>
  <% if shipping_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shipping_address.errors.count, "error") %> prohibited this shipping_address from being saved:</h2>

      <ul>
      <% shipping_address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address_line1 %>
    <%= f.text_field :address_line1 %>
  </div>

  <div class="field">
    <%= f.label :address_line2 %>
    <%= f.text_field :address_line2 %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip_code %>
    <%= f.number_field :zip_code %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :order_id %>
    <%= f.text_field :order_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shipping_addresses/_shipping_address.html.erb
<%= form_for @shipping_address, html: { multipart: true }  do |f| %>
  <div class="col-md-6 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong><h3 class="panel-title" >Shipping Address</h3></strong>
      </div>
      <div class="panel-body">
        <div style="margin-bottom: 12px" class="form-group">
          <%= f.label :"full name"%>:<br />
          <%= f.text_field :name,  autofocus: true, class: "form-control" %>
        </div>

        <div style="margin-bottom: 12px" class="form-group">
          <%= f.label :"address line 1"%>:<br />
          <%= f.text_field :address_line1, placeholder: 'Street address, P.O.Box, Company name',
           autofocus: true, class: "form-control" %>
        </div>

        <div style="margin-bottom: 12px" class="form-group">
          <%= f.label :"address line 2"%>:<br />
          <%= f.text_field :address_line2, placeholder: 'Apartments,suit,unit, building,floor, ... ',
          autofocus: true, class: "form-control" %>
        </div>

        <div style="margin-bottom: 12px" class="form-group">
          <%= f.label :city%>:<br />
          <%= f.text_field :city, autofocus: true, class: "form-control" %>
        </div>

        <div style="margin-bottom: 12px" class="form-group">
          <%= f.label :"State/Province/Region"%>:<br />
          <%= f.text_field :state, autofocus: true, class: "form-control" %>
        </div>

        <div style="margin-bottom: 12px" class="form-group">
          <%= f.label :zip_code%>:<br />
          <%= f.text_field :zip_code, autofocus: true, class: "form-control" %>
        </div>

        <div style="margin-bottom: 12px" class="form-group">
          <%= f.label :country%>:<br />
          <%= f.country_select :country, selected: "US"%>
        </div>

        <div class="actions">
          <%= f.hidden_field :user_id, value: @shipping_address.user.id %>
          <%= f.hidden_field :order_id, value: @shipping_address.order.id %>
          <%= f.submit "continue" %>
        </div>
    </div>
    </div>
  </div>
<% end %>

app/views/shipping_addresses/edit.html.erb
<%= render 'shipping_address'%>

app/views/shipping_addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shipping Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address line1</th>
      <th>Address line2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip code</th>
      <th>Country</th>
      <th>User</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shipping_addresses.each do |shipping_address| %>
      <tr>
        <td><%= shipping_address.name %></td>
        <td><%= shipping_address.address_line1 %></td>
        <td><%= shipping_address.address_line2 %></td>
        <td><%= shipping_address.city %></td>
        <td><%= shipping_address.state %></td>
        <td><%= shipping_address.zip_code %></td>
        <td><%= shipping_address.country %></td>
        <td><%= shipping_address.user %></td>
        <td><%= shipping_address.order %></td>
        <td><%= link_to 'Show', shipping_address %></td>
        <td><%= link_to 'Edit', edit_shipping_address_path(shipping_address) %></td>
        <td><%= link_to 'Destroy', shipping_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shipping Address', new_shipping_address_path %>

app/views/shipping_addresses/new.html.erb
<%= render 'shipping_address' %>

<%= link_to 'Back', shipping_addresses_path %>

app/views/shipping_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shipping_address.name %>
</p>

<p>
  <strong>Address line1:</strong>
  <%= @shipping_address.address_line1 %>
</p>

<p>
  <strong>Address line2:</strong>
  <%= @shipping_address.address_line2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @shipping_address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @shipping_address.state %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @shipping_address.zip_code %>
</p>

<p>
  <strong>Country:</strong>
  <%= @shipping_address.country %>
</p>

<p>
  <strong>User:</strong>
  <%= @shipping_address.user %>
</p>

<p>
  <strong>Order:</strong>
  <%= @shipping_address.order %>
</p>

<%= link_to 'Edit', edit_shipping_address_path(@shipping_address) %> 