config/routes.rb
Rails.application.routes.draw do

  root to: 'store#index', as: 'store'
  #get 'item_search/index'
  resources :items_search, only: :index
  resources :reviews
  resources :shipping_addresses
  resources :orders

  resources :carts, only: :show
  resources :line_items
  resources :categories, only: [:show, :index] do
    resources :items
  end
  resources :items do
    resources :reviews;
  end
  #resources :categories, only: :show



  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '*unmatched_route', to: 'application#raise_not_found'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy
  has_many :items, through: :line_items

  def total
    line_items.collect { |li|
      li.valid? ? (li.quantity * li.item.price) : 0
    }.sum
  end

  def number_of_item
  	line_items.collect(&:quantity).sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  #validates :title, uniqueness: true
  #validates :title, :category, :price, :description, :image, presence: true
  belongs_to :category
  has_many :line_items
  has_many :reviews
  has_attached_file :image, styles: { large:"450x600", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  def update_inventory(inventory)
  	item_to_hash = self.attributes
  	item_to_hash["inventory"] -= inventory
  	self.update(item_to_hash)
  end
end

app/models/item_search_term.rb
class ItemSearchTerm
  attr_reader :where_clause, :where_args, :order

  def initialize(search_term)
    search_term = search_term.downcase

    @where_clause = ""
    @where_args = {}

    searchByTitle(search_term)
  end

  def searchByTitle(search_term)
    @where_clause << case_insensitive_search(:title)
    @where_args[:title] = starts_with(search_term)
    @order = "title ASC"
  end

  def starts_with(search_term)
    "%" + search_term + "%"
  end

  def case_insensitive_search(field_name)
    "lower(#{field_name}) like :#{field_name}"
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end

  def sub_total
    unit_price * quantity
  end

  def finalize
    self[:unit_price] = unit_price
    self[:sub_total] = self[:quantity] * self[:unit_price]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :user
  has_one :cart, through: :user
  has_one :shipping_address, through: :user

  before_create :set_order_status
  before_save :set_total

  def total
  	cart.total
  end

  private

  def set_order_status
	self.order_status_id = 1
  end

  def set_total
  	self[:total] = total
  end


end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item

  def updated_at
    self[:updated_at].strftime('%b %d, %Y');
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :user
  belongs_to :order

  validates_format_of :zip_code,
                  with: /\A\d{5}-\d{4}|\A\d{5}\z/,
                  errors: "should be 12345 or 12345-1234",
                  allow_blank: true
  validates :name, :address_line1, :address_line2, :city, :state, :country, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_one :shipping_address
	has_one :cart
	belongs_to :current_cart, class_name: "Cart"
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:twitter, :facebook, :google_oauth2, :github, :linkedin]



  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@line_items = current_cart.line_items
    render json: @line_items
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  #before_action :authenticate_user!, only: :create
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    #binding.pry
    item = Item.find_by(id: params['item_id'])
    @reviews = item.reviews
    #@reviews = Review.all
    render json: @reviews
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    #binding.pry
    item = Item.find_by(id: params['item_id']);
    #binding.pry
    @review = item.reviews.create(review_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    #binding.pry
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :content, :user_id, :item_id, :upvotes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/item_search_helper.rb
module ItemSearchHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/reviews/_form.html.erb
<%= form_for(review) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :item_id %>
    <%= f.text_field :item_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= review.content %></td>
        <td><%= review.user %></td>
        <td><%= review.item %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user %>
</p>

<p>
  <strong>Item:</strong>
  <%= @review.item %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>